// <auto-generated />
using System;
using MMCProject.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MMCProject.Infrastructure.Migrations
{
    [DbContext(typeof(MMCDBContext))]
    partial class MMCDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MMCProject.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MMCProject.Domain.Entities.SessionTargetAudience", b =>
                {
                    b.Property<Guid>("SessionTargetAudienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetAudienceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionTargetAudienceId");

                    b.HasIndex("TargetAudienceId");

                    b.ToTable("SessionTargetAudiences");
                });

            modelBuilder.Entity("MMCProject.Domain.Entities.SubCategory", b =>
                {
                    b.Property<Guid>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameSubCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("MMCProject.Domain.Entities.TargetAudience", b =>
                {
                    b.Property<Guid>("TargetAudienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameTargetAudience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TargetAudienceId");

                    b.ToTable("TargetAudiences");
                });

            modelBuilder.Entity("MMCProject.Domain.Entities.SessionTargetAudience", b =>
                {
                    b.HasOne("MMCProject.Domain.Entities.TargetAudience", "TargetAudience")
                        .WithMany("SesionTargetAudiences")
                        .HasForeignKey("TargetAudienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetAudience");
                });

            modelBuilder.Entity("MMCProject.Domain.Entities.SubCategory", b =>
                {
                    b.HasOne("MMCProject.Domain.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MMCProject.Domain.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("MMCProject.Domain.Entities.TargetAudience", b =>
                {
                    b.Navigation("SesionTargetAudiences");
                });
#pragma warning restore 612, 618
        }
    }
}
